### ISSUE TITLE
获取车票信息返回的data值是空的

### ISSUE THREAD

**Issue by stonetestf** [YeautyYE/train-ticket-reaper#15]
您好，我这边获取车票信息的时候，返回了：
`{"message":"","code":"00000","data":""}`
我去网页上试着用相同的参数去获取车票是可以获取到的，我debug确定我传的请求与网页上传的也是一致的：
`代码：http://api.12306.com/v1/train/trainInfos?arrStationCode=SHH&deptDate=2018-12-15&deptStationCode=HZH&findGD=false

网页：http://api.12306.com/v1/train/trainInfos?arrStationCode=SHH&deptDate=2018-12-15&deptStationCode=HZH&findGD=false`

为什么我用代码获取车票信息的时候data就为空呢？
![image](https://user-images.githubusercontent.com/24246395/49124879-0174a400-f2f9-11e8-8215-0719ea1663ae.png)

**Comment by YeautyYE** [comment]
应该是他们对ip进行了限制，你尝试在页面上快速刷新几次试试，看看会不会data也为空

**Comment by stonetestf** [comment]
奥，是的，我刷新了几次，页面上确实也拉取不到数据了，这个该怎么办呢？大佬。

**Comment by YeautyYE** [comment]
估计要配合代理ip池来用，具体的我之后看看什么情况

**Comment by honghaoli9898** [comment]
我也是同样的问题,但是要是选择到站是大站的话如(石家庄北京)就有数据，去小站(衡水，邯郸)就没有数据

**Comment by YeautyYE** [comment]
由于那个站点已改成防止相同ip短时间重复刷新,即使是直接在那里手动刷新也会出现这种现象,只能配合代理ip池来用,不太友好.建议直接使用第三方app(如:去哪儿网)进行抢票
