### ISSUE TITLE
座位名称乱码

### ISSUE THREAD

**Issue by ettingshausen** [YeautyYE/train-ticket-reaper#3]
在`application.properties`中设置座位名称，读取后是乱码

## 环境
>IntelliJ IDEA 2018.1.1 (Ultimate Edition)
Build #IU-181.4445.78, built on April 10, 2018
>JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by YeautyYE** [comment]
IDEA编码设为UTF-8试试

**Comment by ettingshausen** [comment]
> File -> Setting -> Editor -> File Encodings
File -> Other Setting -> Default Settins -> Editor -> File Encodings
设置了之后还是有乱码

`application.properties`中加上`spring.http.encoding.force=true`之后就好了
